os:
  - linux
  - osx
services:
  - redis-server
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
env:
  - CXX=g++-4.9
language: node_js
node_js:
  - 5
  - 6
  - 6
  - 7
  - 8
  - 9
  - 10
  - node
  - lts/boron
  - lts/carbon
  - lts/*
  - iojs
after_success:
  - ./node_modules/.bin/istanbul report text-summary lcov
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
