os:
  - linux
  - osx
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
env:
  - CXX=g++-4.9
language: node_js
node_js:
  - 10
  - 12
  - 14
  - node
  - lts/*
after_success:
  - ./node_modules/.bin/istanbul report text-summary lcov
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
