FROM node:14-alpine
MAINTAINER M. Peter <mp@tcs.de>

RUN	mkdir -p /usr/src/
WORKDIR /usr/src/

RUN npm install -g mocha

COPY package.json /usr/src/package.json
RUN npm install

COPY lib/ /usr/src/lib/
COPY test/ /usr/src/test/
COPY index.js /usr/src/
COPY dockertests/test.sh /usr/src/test.sh

RUN chmod +x /usr/src/test.sh

CMD [ "/usr/src/test.sh" ]
